/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-26 03:22:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.membership;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.ansany.member.model.vo.Member;

public final class membership_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664162376726L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1664157968486L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.ansany.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/membership.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

Member m = (Member) session.getAttribute("m");

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- 기본 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-body\">\r\n");
      out.write("	<div class=\"header-fixed\">\r\n");
      out.write("		<div class=\"header-wrap\">\r\n");
      out.write("			<div class=\"header-top\">\r\n");
      out.write("				<div class=\"header-logo\">\r\n");
      out.write("					<a href=\"/index.jsp\"><img src=\"/img/logo2.png\" alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-navi\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/productList.do\">제품</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">헤드폰/이어폰</a></li>\r\n");
      out.write("								<li><a href=\"#\">스피커</a></li>\r\n");
      out.write("								<li><a href=\"#\">턴테이블</a></li>\r\n");
      out.write("								<li><a href=\"#\">워크맨</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"/noticeList.do?reqPage=1\">커뮤니티</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/noticeList.do?reqPage=1\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"/reviewList.do?reqPage=1\">구매후기</a></li>\r\n");
      out.write("								<li><a href=\"/photoList.do\">사진전</a></li>\r\n");
      out.write("								<li><a href=\"/freeBoardList.do?reqPage=1\">자유게시판</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">멤버십</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/membership.do\">등급&혜택 안내</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">고객 서비스</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/faqqnaList.do?reqPage=1&type=faq\">FAQ / Q<span>&</span>A\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\"></a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">직영점 안내</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/map.do\">찾아오시는길</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-icon\">\r\n");
      out.write("					<div class=\"icon-wrap\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/cartView.do\"> <span class=\"material-icons\">shopping_cart</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							");

							if (m == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"loginFrm.do\"> <span class=\"material-icons\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"/myPageFrm.do\"> <span class=\"material-icons\"\r\n");
      out.write("								style=\"color: #5865f5\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#\"> <span class=\"material-icons\">search</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/js/header.js\"></script>\r\n");
      out.write("\n");
      out.write("	<div class=\"membership-container\">\n");
      out.write("		<div class=\"membership-con\">\n");
      out.write("			<div class=\"membership-banner\">\n");
      out.write("				<div class=\"membership-bannerImg\">\n");
      out.write("					<div class=\"membership-bannerText\">\n");
      out.write("						<p>등급 & 혜택 안내</p>\n");
      out.write("						<h1>안사니스토어 멤버십</h1>\n");
      out.write("						<span>안사니스토어 회원이 되시면 다양한 멤버십 혜택을 누리실 수 있습니다!</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"membership-SubContainer\">\n");
      out.write("						<div class=\"membership-bannerSubText\">\n");
      out.write("							<span>안사니스토어 온라인 구매 시 금액대 관계 없이 모두 </span><span\n");
      out.write("								style=\"color: #5865f5; text-decoration: underline; text-underline-position: under;\"><b>무료\n");
      out.write("									배송!</b></span>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"membership-mainContainer\">\n");
      out.write("					<div class=\"membership-content\">\n");
      out.write("						<ul class=\"membership-tabs\">\n");
      out.write("							<li><a href=\"javascript:void(0)\">맴버십</a></li>\n");
      out.write("							<li><a href=\"javascript:void(0)\">프리미엄 서비스</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("					<div>\n");
      out.write("						<div style=\"margin-top: 80px;\">\n");
      out.write("							<div class=\"membership-contentArea\">\n");
      out.write("								<div class=\"membership-contentText\">\n");
      out.write("									<h2>맴버십 안내</h2>\n");
      out.write("									<span>안사니스토어에서 제품 구매시 맴버십 등급에 따라 <span class=\"saleText\">(5\n");
      out.write("											~ 10%)할인</span>이 적용 됩니다.\n");
      out.write("									</span>\n");
      out.write("									<div>\n");
      out.write("										<p>*단, 일부 상품은 할인이 적용되지 않습니다. 상품을 구매하실 때 꼭 확인하시기 바랍니다.</p>\n");
      out.write("										<p style=\"font-size: 20px;\">\n");
      out.write("											<b>- 안사니 스토어 -</b>\n");
      out.write("										</p>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div>\n");
      out.write("						<div>\n");
      out.write("							<div class=\"membership-TableHead\">\n");
      out.write("								<div class=\"membership-Thead\">\n");
      out.write("									<div class=\"Thead-tabTitle\" style=\"width: 240px;\">구분</div>\n");
      out.write("									<div class=\"Thead-tabTitle\">VIP 회원</div>\n");
      out.write("									<div class=\"Thead-tabTitle\">MEMBERSHIP 회원</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"membership-Thead\">\n");
      out.write("									<div class=\"Tbody-subTitle\" style=\"width: 240px;\">회원등급</div>\n");
      out.write("									<div class=\"membership-vipImg\">\n");
      out.write("										<img src=\"img/membership_vipmin.svg\"\n");
      out.write("											style=\"padding-top: 20px;\">\n");
      out.write("									</div>\n");
      out.write("									<div class=\"membership-vipImg\">\n");
      out.write("										<img src=\"img/membership_family2.svg\"\n");
      out.write("											style=\"padding-top: 20px;\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"membership-Thead\">\n");
      out.write("									<div class=\"Tbody-subTitle\" style=\"width: 240px;\">등급기준</div>\n");
      out.write("									<div class=\"\">\n");
      out.write("										<div class=\"membership-Tcontent\">\n");
      out.write("											<p>\n");
      out.write("												구매금액(누적)이 <b>200만원 이상</b>이 되는\n");
      out.write("											</p>\n");
      out.write("											<p>시점 익일부터 VIP 혜택 2년 간 적용</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"\">\n");
      out.write("										<div class=\"membership-Tcontent\">\n");
      out.write("											<p>\n");
      out.write("												구매금액(누적)이 <b>200만원 미만</b>시 익일부터\n");
      out.write("											</p>\n");
      out.write("											<p>MEMBERSHIP 혜택 2년 간 적용</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"membership-Thead\">\n");
      out.write("									<div class=\"Tbody-subTitle\" style=\"width: 240px;\">적립혜택</div>\n");
      out.write("									<div class=\"\">\n");
      out.write("										<div style=\"line-height: 80px;\">\n");
      out.write("											<p>\n");
      out.write("												제품 구매 시 결제 금액의 <b>4%</b> 적립\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<div class=\"\">\n");
      out.write("										<div style=\"line-height: 80px;\">\n");
      out.write("											<p>\n");
      out.write("												제품 구매 시 결제 금액의 <b>2%</b> 적립\n");
      out.write("											</p>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("\n");
      out.write("			<div class=\"prem-contentwrap\">\n");
      out.write("				<div class=\"prem-topcontent\">\n");
      out.write("					<div class=\"prem-topcontent-text\">\n");
      out.write("						<h2>프리미엄 서비스란?</h2>\n");
      out.write("						<p>\n");
      out.write("							고객님께서 안사니제품을 구입하거나 사용 시에 보다 편리하게 사용하실 <br> 수 있도록 제공해 드리는 <b\n");
      out.write("								style=\"color: #5865f5;\">안사니스토어만의 특별한 서비스</b>입니다.\n");
      out.write("						</p>\n");
      out.write("						<ul class=\"prem-serviceicon\">\n");
      out.write("							<li class=\"prem-serviceicons\">기프트\n");
      out.write("								<h3>선물하기 서비스</h3>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-serviceicons\">운송\n");
      out.write("								<h3>퀵/친환경</h3>\n");
      out.write("								<h3 style=\"margin: 0;\">패키지 서비스</h3>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-serviceicons\">비디오\n");
      out.write("								<h3>영상 변환 서비스</h3>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-serviceicons\">수리\n");
      out.write("								<h3>연장 서비스 플랜</h3>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"prem-main-content\">\n");
      out.write("					<div class=\"prem-main-contentwrap\">\n");
      out.write("						<ul class=\"prem-main-one\">\n");
      out.write("							<li class=\"prem-main-lione\">\n");
      out.write("								<div class=\"prem-main-oneImg\">\n");
      out.write("									<img src=\"img/premiumservice1.jpg\" alt=\"\">\n");
      out.write("								</div>\n");
      out.write("								<h3>선물하기 서비스</h3>\n");
      out.write("								<ul>\n");
      out.write("									<li>선물하기 서비스는 <b style=\"color: #5865f5;\">안사니스토어 회원만</b>\n");
      out.write("										온라인 또는 앱에서 이용가능한 서비스입니다.\n");
      out.write("									</li>\n");
      out.write("									<li>선물하기 서비스는 <b style=\"color: #5865f5;\">제품 1건의 구매</b>(결제건)에\n");
      out.write("										한해 이용이 가능합니다.\n");
      out.write("									</li>\n");
      out.write("								</ul>\n");
      out.write("								<p style=\"color: #666; font-size: 0.875em;\">* 제품 1건 결제(구매\n");
      out.write("									수량은 여러개 가능), 복수 배송지 불가</p>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-main-litwo\">\n");
      out.write("								<div class=\"prem-main-oneImg\">\n");
      out.write("									<img src=\"img/premiumservice2.jpg\" alt=\"\">\n");
      out.write("								</div>\n");
      out.write("								<h3>퀵/친환경 패키지 서비스</h3>\n");
      out.write("								<ul>\n");
      out.write("									<li>안사니스토어에서는 온라인 주문 한정으로 친환경 패키징을 제공합니다.</li>\n");
      out.write("									<li>박스/완충 포장재/테이프 모두 종이를 사용하여 환경 보호에 기여합니다.</li>\n");
      out.write("									<li>또한 안전한 배송을 위해 300만원 이상의 제품은 화물배송으로 발송됩니다.</li>\n");
      out.write("									<li>퀵서비스는 구매 금액이 <b style=\"color: #5865f5;\">5만원 이상</b>일 경우\n");
      out.write("										고객 요청에 따라 서울/경기 지역의 퀵서비스 지원이 가능하며,\n");
      out.write("									</li>\n");
      out.write("									<li>제품 구매 금액에 따라 배송 비용이 할증될 수 있습니다.<b\n");
      out.write("										style=\"color: #5865f5;\">퀵서비스 비용은 고객 부담</b>입니다.\n");
      out.write("									</li>\n");
      out.write("									<li><br></li>\n");
      out.write("									<li><b style=\"color: #5865f5;\">#안사니스토어 온라인</b></li>\n");
      out.write("									<li>* 일반배송 : CJ대한통운 택배배송</li>\n");
      out.write("									<li>* 화물배송 : 300만원이상</li>\n");
      out.write("									<li>* 퀵서비스 : 구매 금액이 5만원 이상의 경우 고객 요청에 따라 서울/경기 지역의 퀵서비스\n");
      out.write("										지원이 가능(비용 고객 부담)</li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-main-lithree\">\n");
      out.write("								<div class=\"prem-main-oneImg\">\n");
      out.write("									<img src=\"img/premiumservice3.jpg\" alt=\"\">\n");
      out.write("								</div>\n");
      out.write("								<h3>영상변환 서비스</h3>\n");
      out.write("								<ul>\n");
      out.write("									<li>영상변환 서비스는 고객님께서 소장하고 계시는 비디오 테이프를 <b\n");
      out.write("										style=\"color: #5865f5;\">USB 메모리 또는 DVD 디스크</b>로 변환하여 드리는\n");
      out.write("										서비스입니다.\n");
      out.write("									</li>\n");
      out.write("									<li>변환 가능한 테이프는 <b style=\"color: #5865f5;\">6mm, 8mm 또는\n");
      out.write("											VHS 테이프</b>이며, 가까운 서비스 센터로 비디오 테이프를 가지고 방문하시면 변환 서비스를 받으실 수 있습니다.\n");
      out.write("									</li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("							<li class=\"prem-main-litwo\">\n");
      out.write("								<div class=\"prem-main-oneImg\">\n");
      out.write("									<img src=\"img/premiumservice4.jpg\" alt=\"\">\n");
      out.write("								</div>\n");
      out.write("								<h3>연장 서비스 플랜</h3>\n");
      out.write("								<ul style=\"padding-bottom: 100px;\">\n");
      out.write("									<li style=\"letter-spacing: -.105em;\">연장 서비스 플랜은 소정의 비용으로\n");
      out.write("										제품 구입일로부터 2년 또는 3년 동안 횟수와 금액 상관 없이 안심하고 무상 수리를 받을 수 있는 프리미엄\n");
      out.write("										서비스입니다.</li>\n");
      out.write("									<li>안사니스토어 온라인 및 전화주문을 통해서 구매 가능합니다.</li>\n");
      out.write("									<li>연장 서비스 플랜 적용은<b style=\"color: #5865f5;\">상품 구매일로부터\n");
      out.write("											7일</b> 이후 자동 적용됩니다.\n");
      out.write("									</li>\n");
      out.write("									<li>연장 서비스 플랜 상품은 <b style=\"color: #5865f5;\">무형 상품</b>으로\n");
      out.write("										별도 배송되지 않습니다.\n");
      out.write("									</li>\n");
      out.write("								</ul>\n");
      out.write("							</li>\n");
      out.write("						</ul>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<script src=\"/js/membership.js\"></script>\n");
      out.write("	");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer.css\" />\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-content\">\r\n");
      out.write("		<div class=\"footer-left\">\r\n");
      out.write("			<div class=\"footer-link\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"#\">소비자 피해 보상보험</a></li>\r\n");
      out.write("					<li><a href=\"#\">사이트 맵</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"small-size\">* 본 사이트의 컨텐츠는 저작권법의 보호를 받는 바, 상업적 목적의 무단전재,\r\n");
      out.write("				복사, 배포 등을 금합니다.</p>\r\n");
      out.write("			<p class=\"small-size\">* 소비자피해보상보험 고객님은 안전거래를 위해 현금 등으로 결제 시 저희\r\n");
      out.write("				쇼핑몰에서 가입한 구매안전서비스를 이용하실 수 있습니다.</p>\r\n");
      out.write("			<p class=\"bold-size\">사업장 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19층 A강의실</p>\r\n");
      out.write("			<p class=\"bold-size\">개인정보관리책임자: AnSany TEL: 안사니 고객센터 1588-4444\r\n");
      out.write("				EMAIL: ansany_contact@ansany.com</p>\r\n");
      out.write("			<p class=\"bold-size\">Copyright © An Sany Corporation. All rights\r\n");
      out.write("				reserved.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-right\">\r\n");
      out.write("			<div class=\"followus\">FOLLOW US</div>\r\n");
      out.write("			<div class=\"site-logos\">\r\n");
      out.write("				<a href=\"https://www.facebook.com/sonykorea\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/facebook.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.instagram.com/sonykorea/\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/instagram.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.youtube.com/user/sonystyleblog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/youtube.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://stylezineblog.com/?intcmp=Main_Blog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/blog.png\" class=\"logos\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
