/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-22 12:37:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cart;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.ansany.cart.model.vo.Cart;
import java.util.ArrayList;
import kr.co.ansany.member.model.vo.Member;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1663850042338L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663331062258L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.ansany.cart.model.vo.Cart");
    _jspx_imports_classes.add("kr.co.ansany.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	");

	ArrayList<Cart> list = (ArrayList<Cart>)request.getAttribute("list");
	int totalCount = 0;
	int totalPrice = 0;
	
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>AN SANY 장바구니</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"css/notosans.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/cart.css\">\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

Member m = (Member) session.getAttribute("m");

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- 기본 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-body\">\r\n");
      out.write("	<div class=\"header-fixed\">\r\n");
      out.write("		<div class=\"header-wrap\">\r\n");
      out.write("			<div class=\"header-top\">\r\n");
      out.write("				<div class=\"header-logo\">\r\n");
      out.write("					<a href=\"/index.jsp\"><img src=\"/img/logo2.png\" alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-navi\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/productList.do\">제품</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">헤드폰/이어폰</a></li>\r\n");
      out.write("								<li><a href=\"#\">스피커</a></li>\r\n");
      out.write("								<li><a href=\"#\">턴테이블</a></li>\r\n");
      out.write("								<li><a href=\"#\">워크맨</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"/noticeList.do?reqPage=1\">커뮤니티</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/noticeList.do?reqPage=1\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"#\">구매후기</a></li>\r\n");
      out.write("								<li><a href=\"/photoList.do\">사진전</a></li>\r\n");
      out.write("								<li><a href=\"/freeBoardList.do?reqPage=1\">자유게시판</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">멤버십</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">등급&혜택 안내</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">고객 서비스</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">FAQ / Q<span>&</span>A\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\"></a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">직영점 안내</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/map.do\">찾아오시는길</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-icon\">\r\n");
      out.write("					<div class=\"icon-wrap\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/cartView.do\"> <span class=\"material-icons\">shopping_cart</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							");

							if (m == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"loginFrm.do\"> <span class=\"material-icons\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"/myPageFrm.do\"> <span class=\"material-icons\"\r\n");
      out.write("								style=\"color: #5865f5\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#\"> <span class=\"material-icons\">search</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/js/header.js\"></script>\r\n");
      out.write("\n");
      out.write("	<div class=\"content\">\n");
      out.write("		<div class=\"cart-wrap\">\n");
      out.write("			<div class=\"cart-content\">\n");
      out.write("				<div class=\"cart-title\">\n");
      out.write("					<h1>장바구니</h1>\n");
      out.write("				</div>\n");
      out.write("				<!-- 주문 단계 표시 -->\n");
      out.write("				<div class=\"order-step-wrap\">\n");
      out.write("					<div class=\"order-step\">\n");
      out.write("						<div class=\"order-step-circle active-step\">\n");
      out.write("							<span class=\"material-symbols-outlined\">local_mall</span>\n");
      out.write("						</div>\n");
      out.write("						<p>장바구니</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"order-step-line\"></div>\n");
      out.write("					<div class=\"order-step\">\n");
      out.write("						<div class=\"order-step-circle\">\n");
      out.write("							<span class=\"material-symbols-outlined\">barcode_scanner</span>\n");
      out.write("						</div>\n");
      out.write("						<p>주문·결제</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"order-step-line\"></div>\n");
      out.write("					<div class=\"order-step\">\n");
      out.write("						<div class=\"order-step-circle\">\n");
      out.write("							<span class=\"material-symbols-outlined\">check_circle</span>\n");
      out.write("						</div>\n");
      out.write("						<p>주문 완료</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				");
 if(list.isEmpty()){
      out.write("\n");
      out.write("				<!-- 장바구니 목록 없는 경우 -->\n");
      out.write("				<div class=\"cart-empty\">\n");
      out.write("					<table>\n");
      out.write("						<tr>\n");
      out.write("							<td colspan=\"7\">\n");
      out.write("								<div>\n");
      out.write("									<span>장바구니에 담긴 상품이 없습니다.</span>\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("					</table>\n");
      out.write("					<div class=\"btn-wrap empty\">\n");
      out.write("						<button type=\"button\" onclick=\"location.href='#'\">쇼핑 계속\n");
      out.write("							하기</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				");
} else{
      out.write("\n");
      out.write("				<!-- 장바구니 전체선택/선택삭제 버튼 -->\n");
      out.write("				<div class=\"cart-select\">\n");
      out.write("					<div class=\"selectbox\">\n");
      out.write("						<input type=\"checkbox\" name=\"select-all\" id=\"select-all\">\n");
      out.write("						<label for=\"select-all\" id=\"select-all2\"></label> <label\n");
      out.write("							for=\"select-all\">전체</label>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"select-removebtn\">\n");
      out.write("						<button type=\"button\" id=\"select-removebtn\">선택 삭제</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- 장바구니 목록 -->\n");
      out.write("				<div class=\"cart-table\">\n");
      out.write("					<table>\n");
      out.write("						<thead>\n");
      out.write("							<tr>\n");
      out.write("								<th colspan=\"3\">제품</th>\n");
      out.write("								<th>가격</th>\n");
      out.write("								<th>수량</th>\n");
      out.write("								<th>합계</th>\n");
      out.write("								<th></th>\n");
      out.write("							</tr>\n");
      out.write("						</thead>\n");
      out.write("						<tbody>\n");
      out.write("							");

							for (Cart c : list) {
							
      out.write("\n");
      out.write("							<tr>\n");
      out.write("								<td class=\"cart-checkbox\">\n");
      out.write("									<input type=\"checkbox\" name=\"select-one\" id=\"cart-product\">\n");
      out.write("									<label for=\"cart-product\"></label>\n");
      out.write("								</td>\n");
      out.write("								<td class=\"cart-img\"><img src=\"/img/WH-XB910N(블랙)_1.png\"></td>\n");
      out.write("								<td class=\"cart-name\"><span>");
      out.print(c.getProductName() );
      out.write("</span></td>\n");
      out.write("								<td class=\"cart-price\"><input class=\"cart-price-value\" value=\"");
      out.print(c.getProductPrice() );
      out.write("\" readonly><span>원</span></td>\n");
      out.write("								<td class=\"cart-count\">\n");
      out.write("									<div class=\"cart-count-wrap\">\n");
      out.write("										<button type=\"button\" class=\"cart-count-minus\"><span class=\"material-symbols-outlined\">remove</span></button>\n");
      out.write("										<input type=\"text\" class=\"cart-count-value\" name=\"cart-count\" value=\"");
      out.print(c.getOrderQty() );
      out.write("\">\n");
      out.write("										<button type=\"button\" class=\"cart-count-plus\"><span class=\"material-symbols-outlined\">add</span></button>\n");
      out.write("									</div>\n");
      out.write("								</td>\n");
      out.write("								<td class=\"cart-pricesum\"><input class=\"cart-pricesum-value\" value=\"");
      out.print(c.getProductPrice()*c.getOrderQty() );
      out.write("\" readonly><span>원</span></td>\n");
      out.write("								<td>\n");
      out.write("									<button class=\"cart-removebtn\">\n");
      out.write("										<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("									</button>\n");
      out.write("								</td>\n");
      out.write("							</tr>\n");
      out.write("							");
} 
      out.write("\n");
      out.write("						</tbody>\n");
      out.write("						<!-- 결제예정금액 표시 -->\n");
      out.write("						<tfoot>\n");
      out.write("							<tr>\n");
      out.write("								<td colspan=\"7\">\n");
      out.write("								<span class=\"tfoot-span1\">결제 예정 금액</span>\n");
      out.write("								<span class=\"tfoot-span1\">(총 </span>\n");
      out.write("								<input id=\"total-count\" value=\"0\" readonly>\n");
      out.write("								<span class=\"tfoot-span1\">개)</span>\n");
      out.write("								<input id=\"total-price\" value=\"0\" readonly class=\"tfoot-span2\">\n");
      out.write("								<span class=\"tfoot-span2\">원</span></td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td colspan=\"7\"><span class=\"tfoot-span3\">* 최종 결제금액은 회원등급별 할인율 적용에 따라 달라질 수 있습니다.</span></td>\n");
      out.write("							</tr>\n");
      out.write("						</tfoot>\n");
      out.write("					</table>\n");
      out.write("					<!-- 쇼핑 계속 / 구매 버튼 -->\n");
      out.write("					<div class=\"btn-wrap buy\">\n");
      out.write("						<button type=\"button\" onclick=\"location.href='#'\">쇼핑 계속\n");
      out.write("							하기</button>\n");
      out.write("						<button type=\"button\" onclick=\"location.href='/order.html'\">구매하기</button>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<!-- cart-table종료 -->\n");
      out.write("				");
} 
      out.write("\n");
      out.write("			</div>\n");
      out.write("			<!-- cart-content종료(width:1200px) -->\n");
      out.write("		</div>\n");
      out.write("		<!-- cart-wrap종료(width:100%) -->\n");
      out.write("	</div>\n");
      out.write("	<!-- content종료 -->\n");
      out.write("	");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer.css\" />\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-content\">\r\n");
      out.write("		<div class=\"footer-left\">\r\n");
      out.write("			<div class=\"footer-link\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"#\">소비자 피해 보상보험</a></li>\r\n");
      out.write("					<li><a href=\"#\">사이트 맵</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"small-size\">* 본 사이트의 컨텐츠는 저작권법의 보호를 받는 바, 상업적 목적의 무단전재,\r\n");
      out.write("				복사, 배포 등을 금합니다.</p>\r\n");
      out.write("			<p class=\"small-size\">* 소비자피해보상보험 고객님은 안전거래를 위해 현금 등으로 결제 시 저희\r\n");
      out.write("				쇼핑몰에서 가입한 구매안전서비스를 이용하실 수 있습니다.</p>\r\n");
      out.write("			<p class=\"bold-size\">사업장 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19층 A강의실</p>\r\n");
      out.write("			<p class=\"bold-size\">개인정보관리책임자: AnSany TEL: 안사니 고객센터 1588-4444\r\n");
      out.write("				EMAIL: ansany_contact@ansany.com</p>\r\n");
      out.write("			<p class=\"bold-size\">Copyright © An Sany Corporation. All rights\r\n");
      out.write("				reserved.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-right\">\r\n");
      out.write("			<div class=\"followus\">FOLLOW US</div>\r\n");
      out.write("			<div class=\"site-logos\">\r\n");
      out.write("				<a href=\"https://www.facebook.com/sonykorea\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/facebook.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.instagram.com/sonykorea/\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/instagram.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.youtube.com/user/sonystyleblog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/youtube.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://stylezineblog.com/?intcmp=Main_Blog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/blog.png\" class=\"logos\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("</body>\n");
      out.write("<script src=\"/js/cart.js\"></script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
