/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-25 11:05:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import kr.co.ansany.product.vo.Product;
import kr.co.ansany.member.model.vo.Member;

public final class productView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1664038669508L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663949583926L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.ansany.product.vo.Product");
    _jspx_imports_classes.add("kr.co.ansany.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	Product p = (Product)request.getAttribute("p");
    	int productCount = 1;
    
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>제품 상세 페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/productView.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Noto_Sans.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

Member m = (Member) session.getAttribute("m");

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- 기본 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-body\">\r\n");
      out.write("	<div class=\"header-fixed\">\r\n");
      out.write("		<div class=\"header-wrap\">\r\n");
      out.write("			<div class=\"header-top\">\r\n");
      out.write("				<div class=\"header-logo\">\r\n");
      out.write("					<a href=\"/index.jsp\"><img src=\"/img/logo2.png\" alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-navi\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/productList.do\">제품</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">헤드폰/이어폰</a></li>\r\n");
      out.write("								<li><a href=\"#\">스피커</a></li>\r\n");
      out.write("								<li><a href=\"#\">턴테이블</a></li>\r\n");
      out.write("								<li><a href=\"#\">워크맨</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"/noticeList.do?reqPage=1\">커뮤니티</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/noticeList.do?reqPage=1\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"/reviewList.do?reqPage=1\">구매후기</a></li>\r\n");
      out.write("								<li><a href=\"/photoList.do\">사진전</a></li>\r\n");
      out.write("								<li><a href=\"/freeBoardList.do?reqPage=1\">자유게시판</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">멤버십</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">등급&혜택 안내</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">고객 서비스</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">FAQ / Q<span>&</span>A\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\"></a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">직영점 안내</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/map.do\">찾아오시는길</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-icon\">\r\n");
      out.write("					<div class=\"icon-wrap\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/cartView.do\"> <span class=\"material-icons\">shopping_cart</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							");

							if (m == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"loginFrm.do\"> <span class=\"material-icons\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"/myPageFrm.do\"> <span class=\"material-icons\"\r\n");
      out.write("								style=\"color: #5865f5\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#\"> <span class=\"material-icons\">search</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/js/header.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- productView 시작 -->\r\n");
      out.write("	<div class=\"product-view-wrapper\">\r\n");
      out.write("        <div class=\"product-view-img\">\r\n");
      out.write("            <img src=\"/upload/prodImg/");
      out.print(p.getProductImg());
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"product-view-content\">\r\n");
      out.write("            <div class=\"product-view-info\">\r\n");
      out.write("                <p class=\"product-message\">NEW</p>\r\n");
      out.write("                <p class=\"product-name\">");
      out.print(p.getProductName());
      out.write("</p>\r\n");
      out.write("                <p class=\"product-info\">");
      out.print(p.getProductInfo());
      out.write("</p>\r\n");
      out.write("                <p class=\"product-comment\">이 제품은 기획전을 통해 구매하시면 더 많은 혜택을 받으실 수 있습니다.</p>\r\n");
      out.write("                <div class=\"product-price-div\">\r\n");
      out.write("                   	<p class=\"product-price\">");
      out.print(p.getProductPrice());
      out.write("원</p>\r\n");
      out.write("                    <p class=\"product-delivery\">무료배송</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p class=\"membership-comment\">회원별 마일리지 적립혜택<span class=\"icon-question\">!</span></p>\r\n");
      out.write("                <ul class=\"membership-ul\">\r\n");
      out.write("                    <li class=\"vip\">\r\n");
      out.write("                        <span class=\"vip-mark\"></span>\r\n");
      out.write("                        <div class=\"save-info\">\r\n");
      out.write("                            <span class=\"percent\">VIP 4%</span><br>\r\n");
      out.write("                            <span class=\"num\">");
      out.print((int)(p.getProductPrice()*0.04));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"membership\">\r\n");
      out.write("                        <span class=\"membership-mark\"></span>\r\n");
      out.write("                        <div class=\"save-info\">\r\n");
      out.write("                            <span class=\"percent\">MEMBERSHIP 2%</span><br>\r\n");
      out.write("                            <span class=\"num\">");
      out.print((int)(p.getProductPrice()*0.02));
      out.write("</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"product-select-box\">\r\n");
      out.write("                    <p>제품선택</p>\r\n");
      out.write("                    <select name=\"select-btn\" id=\"select-btn\">\r\n");
      out.write("                        <option value=\"\" disabled selected>제품을 선택하세요.</option>\r\n");
      out.write("                        <option value=\"\" id=\"select-option\">제품명 : ");
      out.print(p.getProductName());
      out.write("</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <div class=\"product-option-box\">\r\n");
      out.write("                        <p>제품</p>\r\n");
      out.write("                        <span>제품명 : ");
      out.print(p.getProductName());
      out.write("</span>\r\n");
      out.write("                        <div class=\"count-box\">\r\n");
      out.write("                            <button class=\"minus\">-</button>\r\n");
      out.write("                            <input type=\"text\" class=\"count\" value=\"");
      out.print(productCount );
      out.write("\">\r\n");
      out.write("                            <button class=\"plus\">+</button>\r\n");
      out.write("                            <p>");
      out.print(p.getProductPrice()*productCount);
      out.write("원</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-result-price\">\r\n");
      out.write("                    <p>총 상품금액(총 ");
      out.print(productCount-1 );
      out.write("개)</p>\r\n");
      out.write("                    <span>");
      out.print(p.getProductPrice()*(productCount-1));
      out.write("원</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"result-btn-box\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <a href=\"#\" class=\"heart-btn\"><li></li></a>\r\n");
      out.write("                        <a href=\"/cartView.do\" class=\"cart-btn\"><li></li></a>\r\n");
      out.write("                        <a href=\"#\" class=\"gift-btn\"><li></li></a>\r\n");
      out.write("                        <a href=\"#\" class=\"buy-btn\"><li>바로 구매하기</li></a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<!-- productView 끝 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		 function addComma(value){\r\n");
      out.write("	   	 	value = value.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\");\r\n");
      out.write("	   	 	return value;\r\n");
      out.write("	    };\r\n");
      out.write("	    \r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("	    $(\"#select-btn\").on(\"change\",function(){\r\n");
      out.write("	    	$(\".product-option-box\").css(\"display\",\"inline-block\");\r\n");
      out.write("	    });\r\n");
      out.write("	    ");
      out.write("\r\n");
      out.write("	  //수량 증가(+)버튼 클릭 시 1개 증가\r\n");
      out.write("	    $(\".plus\").on(\"click\",function(){\r\n");
      out.write("	    	console.log(\"클릭되니??\");\r\n");
      out.write("	        let productCount = $(this).prev();\r\n");
      out.write("	        $(\".count\").val(Number(productCount.val())+1);\r\n");
      out.write("	        //가격과 합계 불러오기\r\n");
      out.write("	        let cartPrice = $(this).parent().parent().prev().find(\"input\");\r\n");
      out.write("	        let cartPriceSum = $(this).parent().parent().next().find(\"input\");\r\n");
      out.write("	        //가격에서 콤마 제거 후 합계(가격*수량)계산\r\n");
      out.write("	        let numPrice = removeComma(cartPrice.val());\r\n");
      out.write("	        let numPriceSum = numPrice*cartCount.val();\r\n");
      out.write("	        console.log(typeof numPriceSum, numPriceSum);\r\n");
      out.write("	        cartPriceSum.val(numPriceSum);\r\n");
      out.write("	        //변경한 수량과 합계를 총수량, 결제예정금액에 반영\r\n");
      out.write("	        calCheckedCount();\r\n");
      out.write("	        calCheckedPrice();\r\n");
      out.write("	        //계산한 합계에 콤마 추가\r\n");
      out.write("	        console.log(typeof numPriceSum, numPriceSum);\r\n");
      out.write("	        numPriceSum = addComma(numPriceSum);\r\n");
      out.write("	        console.log(typeof numPriceSum, numPriceSum);\r\n");
      out.write("	        cartPriceSum.val(numPriceSum);\r\n");
      out.write("	    });\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer.css\" />\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-content\">\r\n");
      out.write("		<div class=\"footer-left\">\r\n");
      out.write("			<div class=\"footer-link\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"#\">소비자 피해 보상보험</a></li>\r\n");
      out.write("					<li><a href=\"#\">사이트 맵</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"small-size\">* 본 사이트의 컨텐츠는 저작권법의 보호를 받는 바, 상업적 목적의 무단전재,\r\n");
      out.write("				복사, 배포 등을 금합니다.</p>\r\n");
      out.write("			<p class=\"small-size\">* 소비자피해보상보험 고객님은 안전거래를 위해 현금 등으로 결제 시 저희\r\n");
      out.write("				쇼핑몰에서 가입한 구매안전서비스를 이용하실 수 있습니다.</p>\r\n");
      out.write("			<p class=\"bold-size\">사업장 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19층 A강의실</p>\r\n");
      out.write("			<p class=\"bold-size\">개인정보관리책임자: AnSany TEL: 안사니 고객센터 1588-4444\r\n");
      out.write("				EMAIL: ansany_contact@ansany.com</p>\r\n");
      out.write("			<p class=\"bold-size\">Copyright © An Sany Corporation. All rights\r\n");
      out.write("				reserved.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-right\">\r\n");
      out.write("			<div class=\"followus\">FOLLOW US</div>\r\n");
      out.write("			<div class=\"site-logos\">\r\n");
      out.write("				<a href=\"https://www.facebook.com/sonykorea\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/facebook.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.instagram.com/sonykorea/\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/instagram.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.youtube.com/user/sonystyleblog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/youtube.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://stylezineblog.com/?intcmp=Main_Blog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/blog.png\" class=\"logos\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
