/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-09-22 12:39:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.ansany.member.model.vo.Member;

public final class joinAgree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1663850042338L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1663331062258L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.ansany.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>약관동의</title>\n");
      out.write("<style>\n");
      out.write("	.header-logo>a>img{\n");
      out.write("		margin-bottom: 14px;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<!--css-->\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/joinAgree.css\">\n");
      out.write("<!--fonts-->\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/Noto_Sans.css\">\n");
      out.write("<!--구글 아이콘-->\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\n");
      out.write("<!--jquery-->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");

Member m = (Member) session.getAttribute("m");

      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("<!-- 기본 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/header.css\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-body\">\r\n");
      out.write("	<div class=\"header-fixed\">\r\n");
      out.write("		<div class=\"header-wrap\">\r\n");
      out.write("			<div class=\"header-top\">\r\n");
      out.write("				<div class=\"header-logo\">\r\n");
      out.write("					<a href=\"/index.jsp\"><img src=\"/img/logo2.png\" alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-navi\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"/productList.do\">제품</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">헤드폰/이어폰</a></li>\r\n");
      out.write("								<li><a href=\"#\">스피커</a></li>\r\n");
      out.write("								<li><a href=\"#\">턴테이블</a></li>\r\n");
      out.write("								<li><a href=\"#\">워크맨</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"/noticeList.do?reqPage=1\">커뮤니티</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/noticeList.do?reqPage=1\">공지사항</a></li>\r\n");
      out.write("								<li><a href=\"#\">구매후기</a></li>\r\n");
      out.write("								<li><a href=\"/photoList.do\">사진전</a></li>\r\n");
      out.write("								<li><a href=\"/freeBoardList.do?reqPage=1\">자유게시판</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">멤버십</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">등급&혜택 안내</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">고객 서비스</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"#\">FAQ / Q<span>&</span>A\r\n");
      out.write("								</a></li>\r\n");
      out.write("								<li><a href=\"#\"></a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("						<li><a href=\"#\">직영점 안내</a>\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"/map.do\">찾아오시는길</a></li>\r\n");
      out.write("							</ul></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"header-icon\">\r\n");
      out.write("					<div class=\"icon-wrap\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"/cartView.do\"> <span class=\"material-icons\">shopping_cart</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							");

							if (m == null) {
							
      out.write("\r\n");
      out.write("							<a href=\"loginFrm.do\"> <span class=\"material-icons\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							} else {
							
      out.write("\r\n");
      out.write("							<a href=\"/myPageFrm.do\"> <span class=\"material-icons\"\r\n");
      out.write("								style=\"color: #5865f5\">person</span>\r\n");
      out.write("							</a>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<a href=\"#\"> <span class=\"material-icons\">search</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/js/header.js\"></script>\r\n");
      out.write("\n");
      out.write("	<div class=\"content\">\n");
      out.write("		<div class=\"join-agree-wrap\">\n");
      out.write("			<div class=\"agree-header\">\n");
      out.write("				<h1>안사니 스토어</h1>\n");
      out.write("				<div class=\"header-text\">\n");
      out.write("					<span>안사니와 안사니 고객지원 사이트는 하나의 아이디와 비밀번호로 운영됩니다.</span> <span>안사니\n");
      out.write("						고객지원 사이트의 이용약관에 함께 동의하시면,</span> <span>하나의 아이디로 고객지원 사이트를 편리하게\n");
      out.write("						이용하실수 있습니다.</span>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!--agree-header 끝-->\n");
      out.write("			<div class=\"contentdetail\">\n");
      out.write("				<div class=\"all-box\">\n");
      out.write("					<span class=\"allAgree-title\">약관 전체 동의</span>\n");
      out.write("					<div class=\"form-check form-switch\">\n");
      out.write("						<label class=\"form-check-label\" for=\"flexSwitchCheckDefault\">\n");
      out.write("							<input class=\"form-check-input\" type=\"checkbox\" role=\"switch\"\n");
      out.write("							id=\"flexSwitchCheckDefault\"> <span class=\"toggle\"></span>\n");
      out.write("						</label>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agree-check-box\">\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk00\"\n");
      out.write("								name=\"essential\"> <label for=\"chk00\">[필수]안사니스토어\n");
      out.write("								쇼핑몰 이용약관 동의</label> <a href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk01\"\n");
      out.write("								name=\"essential\"> <label for=\"chk01\">[필수]안사니\n");
      out.write("								고객지원 사이트 이용약관 동의</label> <a href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk02\"\n");
      out.write("								name=\"essential\"> <label for=\"chk02\">[필수]회원가입\n");
      out.write("								개인정보 수집에 관한 동의</label> <a href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk03\"\n");
      out.write("								name=\"essential\"> <label for=\"chk03\">[필수]개인정보\n");
      out.write("								위탁에 관한 동의</label> <a href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk04\"> <label\n");
      out.write("								for=\"chk04\">[선택]이벤트 등 프로모션 알림 메일 수신</label> <a\n");
      out.write("								href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"chk_cell\">\n");
      out.write("						<div class=\"check\">\n");
      out.write("							<input type=\"checkbox\" class=\"inp_check\" id=\"chk05\"> <label\n");
      out.write("								for=\"chk05\">[선택]이벤트 등 프로모션 알림 SMS 수신</label> <a\n");
      out.write("								href=\"javascript:void(0)\" class=\"btn_view\">전체보기</a>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!--contentdetail 끝-->\n");
      out.write("			<div class=\"agree-footer\">\n");
      out.write("				<div class=\"agree-btn-box\">\n");
      out.write("					<a href=\"#\">\n");
      out.write("						<button type=\"button\" class=\"btn-agree\">동의</button>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!--agree-footer 끝-->\n");
      out.write("		</div>\n");
      out.write("		<!--join-agree-wrap 끝-->\n");
      out.write("	</div>\n");
      out.write("	<!--컨텐츠 끝-->\n");
      out.write("	<div class=\"modal-wrap\">\n");
      out.write("		<div class=\"modal\">\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>안사니스토어 쇼핑몰 이용약관 동의</h2>\n");
      out.write("						<strong>제1장 총칙</strong> <strong>제1조 (목적)</strong> <span>본\n");
      out.write("							약관은 안사니코리아 주식회사 (이하 회사라 한다.)가 운영하는 안사니코리아 공식 웹사이트(이하 공식 웹사이트라\n");
      out.write("							한다.)가 제공하는 인터넷관련 서비스 (이하 서비스라 한다.)를 이용함에 있어 공식 웹사이트와 이용자의 권리, 의무\n");
      out.write("							및 책임사항을 규정하는 것을 목적으로 합니다.</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"agreeTextContent\">\n");
      out.write("						<strong>제2조 (정의)</strong> <span> ① Ansany Store라 함은 회사가 재화\n");
      out.write("							또는 용역(이하 재화등이라 함)을 이용자에게 제공하기위해 컴퓨터등 정보통신설비를 이용하여 상품을 거래할 수 있도록\n");
      out.write("							설정한 가상의 영업장을 말하며 아울러 사이버몰을 운영하는 사업자의 의미로도 사용합니다. ② 이용자라 함은 Ansany\n");
      out.write("							Store에 접속하여 이 약관에 따라 Ansany Store가 제공하는 서비스를 받는 회원 및 비회원을 말합니다. ③\n");
      out.write("							회원이라 함은 Ansany Store에 개인정보를 제공하여 회원등록을 한 자로서 Ansany Store가 제공하는\n");
      out.write("							정보를 지속적으로 받으며 Ansany Store의 서비스를 계속 제공받을 수 있는 자를 말합니다. ④ 비회원이라 함은\n");
      out.write("							회원에 가입하지 않고 서비스를 이용하는 자를 말합니다. ⑤ 회원아이디(ID)라 함은 회원의 식별과 서비스 이용을 위해\n");
      out.write("							회원이 정하고 Ansany Store가 승인하는 문자 또는 숫자의 조합으로 회사가 운영하는 다른 인터넷사이트와\n");
      out.write("							동일하게 사용하게 됩니다. 단, Ansany Store에 가입한 회원이 안사니 코리아가 제공하는 콜럼비아 트라이스타\n");
      out.write("							사이트에 회원으로 가입하는 경우, Ansany Store와 동일한 회원 아이디(ID)와 비밀번호를 사용해야 합니다.\n");
      out.write("							⑥ Ansany Store 멤버십제도는 Ansany Store 온라인 가입 회원에게 해당되는 것으로 상품구입시\n");
      out.write("							마일리지 제공 및 기타 이벤트 참가기회 제공 등 차별화된 서비스를 제공하는 것을 말합니다. </span> <strong>제3조\n");
      out.write("							(약관의 게시, 효력, 개정)</strong> <span> ① Ansany Store는 본 약관의 내용과 상호 및 대표자\n");
      out.write("							성명, 영업소소재지(및 소비자의 불만을 처리할 수 있는 곳의 주소), 전화번호, fax번호, 전자우편주소,\n");
      out.write("							사업자등록번호, 통신판매업 신고번호, 개인정보관리책임자 등을 이용자가 알 수 있도록 Ansany Store의\n");
      out.write("							초기화면에 게시합니다. 단, 약관의 내용은 이용자가 연결화면을 통하여 볼 수 있도록 할 수 있습니다. ② Ansany\n");
      out.write("							Store는 이용자가 약관에 동의하기에 앞서 약관에 정하여져 있는 내용중 청약철회, 배송책임, 환불조건 등과 같은\n");
      out.write("							중요한 내용을 이용자가 이해할 수 있도록 별도의 연결화면 또는 팝업화면 등을 제공하여 이용자의 확인을 구하여야\n");
      out.write("							합니다. ③ 본 약관은 전자상거래등에서의 소비자보호에 관한 법률, 약관의 규제등에 관한 법률, 전자거래기본법,\n");
      out.write("							전자서명법, 정보통신망이용촉진 및 정보보호등에 관한 법률, 방문판매등에 관한 법률, 소비자보호법등 관련법을 위반하지\n");
      out.write("							않는 범위내에서 개정될 수 있습니다. ④ 회사가 본 약관을 이용자에게 불리하게 변경하는 경우에는 최소한 30일 이상의\n");
      out.write("							사전 유예기간을 두고 공지합니다. 이 경우 Ansany Store는 개정전 내용과 개정후 내용을 명확하게 비교하여\n");
      out.write("							이용자가 알기 쉽도록 표시합니다. ⑤ 회사가 약관을 개정할 경우에는 그 개정약관은 적용일자 이후에 체결된 계약에만\n");
      out.write("							적용되고 그 이전에 이미 체결된 계약에 관해서는 개정전의 약관이 적용됩니다. 단, 이미 계약을 체결한 이용자가\n");
      out.write("							개정약관의 적용을 받기를 원하는 뜻을 제④항의 공지기간내 Ansany Store에 송신하여 Ansany Store의\n");
      out.write("							동의를 받은 경우는 개정약관 조항이 적용됩니다. ⑥ 본 약관에 명시되지 않은 사항과 본 약관의 해석에 관해서는\n");
      out.write("							전자상거래등에서의 소비자보호에 관한 법, 약관의규제등에 관한 법,공정거래위원회가 정하는 전자상거래등에서의\n");
      out.write("							소비자보호지침 및 관계법령 또는 상관례에 따릅니다. </span>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("					<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>안사니 고객지원 사이트(SCS) 이용약관 동의</h2>\n");
      out.write("						<strong>제1장 총칙</strong> <strong>제1조 (목적)</strong> <span>본\n");
      out.write("							약관은 안사니코리아주식회사 (이하 회사라 합니다.)가 운영하는 사이버 고객지원 페이지인 AnSany Customer\n");
      out.write("							Station (이하 SCS 이라 합니다.)이 제공하는 인터넷관련 서비스 (이하 서비스라 합니다.)를 이용함에 있어\n");
      out.write("							SCS와 이용자의 권리, 의무 및 책임사항을 규정하는 것을 목적으로 합니다. 본 약관은 \"온라인 수리요금 결제 서비스\n");
      out.write("							이용약관\" 및 \" 안사니 아카데미 유료강좌 이용약관\"에서 특별히 정하지 않은 사항에 대해서도 공통적으로 적용됩니다.</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"agreeTextContent\">\n");
      out.write("						<strong>제2조 (정의)</strong> <span> ① 이용자라 함은 SCS에 접속하여 이 약관에\n");
      out.write("							따라 SCS가 제공하는 서비스를 받는 회원 및 비회원을 말합니다. ② 회원이라 함은 SCS에 개인정보를 제공하여\n");
      out.write("							회원등록을 한 자로서, SCS의 정보를 지속적으로 제공받으며, SCS가 제공하는 서비스를 계속적으로 이용할 수 있는\n");
      out.write("							자를 말합니다. ③ 비회원이라 함은 회원에 가입하지 않고 SCS에서 제공하는 서비스를 이용하는 자를 말합니다. ④\n");
      out.write("							회원아이디(ID)라 함은 회원의 식별과 서비스 이용을 위해 회원이 정하고 SCS가 승인하는 문자 또는 숫자의 조합으로\n");
      out.write("							회사가 운영하는 다른 인터넷사이트와 동일하게 사용하게 됩니다. </span> <strong>제3조 (약관의 게시,\n");
      out.write("							효력, 개정)</strong> <span> ① SCS는 본 약관의 내용과 상호 및 대표자 성명, 영업소소재지(및 소비자의\n");
      out.write("							불만을 처리할 수 있는 곳의 주소), 전화번호, fax번호, 전자우편주소, 사업자등록번호, 통신판매업 신고번호,\n");
      out.write("							개인정보관리책임자 등을 이용자가 알 수 있도록 SCS의 초기화면에 게시합니다. 단, 약관의 내용은 이용자가 연결화면을\n");
      out.write("							통하여 볼 수 있도록 할 수 있습니다. ② SCS는 이용자가 약관에 동의하기에 앞서 약관에 정하여져 있는 내용 중\n");
      out.write("							청약철회, 배송책임, 환불조건 등과 같은 중요한 내용을 이용자가 이해할 수 있도록 별도의 연결화면 또는 팝업화면 등을\n");
      out.write("							제공하여 이용자의 확인을 구하여야 합니다. ③ 본 약관은 전자상거래 등에서의 소비자보호에 관한 법률, 약관의 규제\n");
      out.write("							등에 관한 법률, 전자거래기본법, 전자서명법, 정보통신망이용촉진 및 정보보호 등에 관한 법률, 방문판매 등에 관한\n");
      out.write("							법률, 소비자보호법 등 관련법을 위반하지 않는 범위 내에서 개정될 수 있습니다. ④ 회사가 본 약관을 개정할 경우\n");
      out.write("							적용일자 및 개정사유를 명시하여 현행약관과 함께SCS초기화면에 적용일자 7일 이전부터 적용일자 전일까지 공지합니다.\n");
      out.write("							다만 이용자에게 불리하게 약관내용을 변경하는 경우에는 최소한 30일 이상의 사전 유예기간을 두고 공지합니다. 이 경우\n");
      out.write("							SCS는 개정 전 내용과 개정 후 내용을 명확하게 비교하여 이용자가 알기 쉽도록 표시합니다. ⑤ 회사가 약관을 개정할\n");
      out.write("							경우에는 그 개정약관은 적용일자 이후에 체결된 계약에만 적용되고 그 이전에 이미 체결된 계약에 관해서는 개정전의\n");
      out.write("							약관이 적용됩니다. 단, 이미 계약을 체결한 이용자가 개정약관의 적용을 받기를 원하는 뜻을 제④항의 공지기간 내\n");
      out.write("							SCS에 송신하여 SCS의 동의를 받은 경우는 개정약관 조항이 적용됩니다. ⑥ 본 약관에 명시되지 않은 사항과 본\n");
      out.write("							약관의 해석에 관해서는 전자상거래 등에서의 소비자보호에 관한 법, 약관의 규제 등에 관한 법,공정거래위원회가 정하는\n");
      out.write("							전자상거래 등에서의 소비자보호지침 및 관계법령 또는 상관례에 따릅니다. </span>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("					<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>회원가입 개인정보 수집에 관한 동의</h2>\n");
      out.write("						<strong>수집, 이용목적</strong> <span>서비스 제공에 관한 계약 및 서비스제공에 따른\n");
      out.write("							요금정산, 회원관리</span>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"agreeTextContent\">\n");
      out.write("						<strong>수집하는 개인정보 항목</strong>\n");
      out.write("						<div class=\"layer_tbl\">\n");
      out.write("							<table>\n");
      out.write("								<colgroup>\n");
      out.write("									<col style=\"width: 35%;\">\n");
      out.write("									<col>\n");
      out.write("								</colgroup>\n");
      out.write("								<tread>\n");
      out.write("								<tr>\n");
      out.write("									<th scope=\"col\">회원가입</th>\n");
      out.write("									<th scope=\"col\">수집하는 개인정보 항목</th>\n");
      out.write("								</tr>\n");
      out.write("								</tread>\n");
      out.write("								<tbody>\n");
      out.write("									<tr>\n");
      out.write("										<td>일반 회원 가입 시</td>\n");
      out.write("										<td>필수 항목 : 이메일 주소 (아이디),성명, 비밀번호, 휴대폰번호, 생년월일, 성별 최초상품\n");
      out.write("											주문시 : 주소</td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td>외국인 회원 가입 시</td>\n");
      out.write("										<td>필수 항목 : 이메일 주소 (아이디),성명, 비밀번호, 휴대폰번호, 생년월일, 성별 최초상품\n");
      out.write("											주문시 : 주소</td>\n");
      out.write("									</tr>\n");
      out.write("									<tr>\n");
      out.write("										<td>법인 회원 가입 시</td>\n");
      out.write("										<td>필수 항목 : 이메일 주소 (아이디),성명, 비밀번호, 휴대폰번호, 생년월일, 성별 최초상품\n");
      out.write("											주문시 : 주소</td>\n");
      out.write("									</tr>\n");
      out.write("								</tbody>\n");
      out.write("							</table>\n");
      out.write("						</div>\n");
      out.write("						<!--테이블 끝-->\n");
      out.write("						<strong>개인정보 보유 및 이용기간</strong> <span>수집된 개인정보는 회원 탈퇴및 서비스\n");
      out.write("							종료시까지 보관됩니다. 단, 회원가입 후 1년동안 이용하지 않은 고객의 개인정보는 파기됩니다.</span> <strong>개인정보\n");
      out.write("							수집에 거부할수 있으며, 거부할 경우 회원가입이 제한됩니다.</strong>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("					<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>개인정보 위탁에 관한 동의</h2>\n");
      out.write("						<span>회사는 원활한 고객서비스 이행을 위해 아래와 같이 외부 전문 업체에 개인정보를 위탁 운영하고\n");
      out.write("							있습니다. 개인정보 위탁에 대하여 거부할 수 있으며 거부 시 회원가입이 제한됩니다.</span>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("					<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>이벤트 등 프로모션 알림 메일 수신</h2>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"agreeTextContent\">\n");
      out.write("						<strong>수집 이용목적</strong> <span> 마케팅 등 프로모션 이메일 및 SNS 알림 </span> <strong>수집하는\n");
      out.write("							개인정보 항목</strong> <span> 필수 : 이메일 주소(아이디), 성명, 휴대폰번호, 생년월일 </span> <strong>개인정보\n");
      out.write("							보유 및 이용기간</strong> <span> 수집된 개인정보는 회원 탈퇴 및 서비스 종료 시까지 보관됩니다. 단,\n");
      out.write("							회원가입 후 1년 동안 이용하지 않은 고객의 개인정보는 파기됩니다. </span> <strong>개인정보 수집에\n");
      out.write("							거부할 수 있으며, 동의를 거부할 경우 이에 따른 불이익은 없습니다.</strong>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("					<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"allViewAgree\">\n");
      out.write("				<div class=\"agreeText\">\n");
      out.write("					<div class=\"agreeTextTitle\">\n");
      out.write("						<span class=\"material-symbols-outlined\">close</span>\n");
      out.write("						<h2>이벤트 등 프로모션 알림 sms 수신</h2>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"agreeTextContent\">\n");
      out.write("						<strong>수집 이용목적</strong> <span> 마케팅 등 프로모션 이메일 및 SNS 알림 </span> <strong>수집하는\n");
      out.write("							개인정보 항목</strong> <span> 필수 : 이메일 주소(아이디), 성명, 휴대폰번호, 생년월일 </span> <strong>개인정보\n");
      out.write("							보유 및 이용기간</strong> <span> 수집된 개인정보는 회원 탈퇴 및 서비스 종료 시까지 보관됩니다. 단,\n");
      out.write("							회원가입 후 1년 동안 이용하지 않은 고객의 개인정보는 파기됩니다. </span> <strong>개인정보 수집에\n");
      out.write("							거부할 수 있으며, 동의를 거부할 경우 이에 따른 불이익은 없습니다.</strong>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"agreeOneBtn\">\n");
      out.write("						<button type=\"button\" class=\"chkBtn\">동의</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<!--modal 끝-->\n");
      out.write("	</div>\n");
      out.write("	<!--modal-wrap끝-->\n");
      out.write("	");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/footer.css\" />\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"footer-content\">\r\n");
      out.write("		<div class=\"footer-left\">\r\n");
      out.write("			<div class=\"footer-link\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"#\">소비자 피해 보상보험</a></li>\r\n");
      out.write("					<li><a href=\"#\">사이트 맵</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<p class=\"small-size\">* 본 사이트의 컨텐츠는 저작권법의 보호를 받는 바, 상업적 목적의 무단전재,\r\n");
      out.write("				복사, 배포 등을 금합니다.</p>\r\n");
      out.write("			<p class=\"small-size\">* 소비자피해보상보험 고객님은 안전거래를 위해 현금 등으로 결제 시 저희\r\n");
      out.write("				쇼핑몰에서 가입한 구매안전서비스를 이용하실 수 있습니다.</p>\r\n");
      out.write("			<p class=\"bold-size\">사업장 주소: 서울특별시 영등포구 선유동2로 57 이레빌딩 19층 A강의실</p>\r\n");
      out.write("			<p class=\"bold-size\">개인정보관리책임자: AnSany TEL: 안사니 고객센터 1588-4444\r\n");
      out.write("				EMAIL: ansany_contact@ansany.com</p>\r\n");
      out.write("			<p class=\"bold-size\">Copyright © An Sany Corporation. All rights\r\n");
      out.write("				reserved.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer-right\">\r\n");
      out.write("			<div class=\"followus\">FOLLOW US</div>\r\n");
      out.write("			<div class=\"site-logos\">\r\n");
      out.write("				<a href=\"https://www.facebook.com/sonykorea\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/facebook.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.instagram.com/sonykorea/\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/instagram.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://www.youtube.com/user/sonystyleblog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/youtube.png\" class=\"logos\"></a> <a\r\n");
      out.write("					href=\"https://stylezineblog.com/?intcmp=Main_Blog\" target=\"_blank\"><img\r\n");
      out.write("					src=\"/img/blog.png\" class=\"logos\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\n");
      out.write("	<script src=\"/js/header.js\"></script>\n");
      out.write("	<script src=\"/js/joinAgree.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
